---
title: "DATA604 - Simulation Overview"
author: "Sreejaya, Suman, Vuthy"
date: "December 6, 2016"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Work Plan Overview
This project will be split into 2 main parts.

- Energy Generation
- Energy Consumption

## Energy Generation

### Data Collection/Preperation 

- Find Dataset to help us estimate/model usable daylight for a specific location
- Find weather dataset to predict cloudiness or precipitation
- Find information regaurding how much power is generated with a PV system. i.e. a 4kw sytem needs 5 panels or 30 square feet of panels.

### Simulation

- Simulate passage of time (Day to night)
- Simulate weather pattern (Rain, snow, sunny)


## Energy Consumption

### Data Collection/Preparation

- What is average family size (adults and children)
- Family composition. Is the house empty during work hours? 
- What is the roof size and how much panels can it hold
- Typical household electricity usage.
- Typical electrical appliance usage in the house
  - Number of TVs, Refridgerator 
  - Number of light bulbs and how long they are in use
  - Router/Modem
  - etc
  
### Simulation

- Animation of appliance (in use or not)
- Animation of family (home or not)
- 3D Animation/modeling